--
-- V1 — baseline schema.
--
-- Captured from the running database on 14 Aug 2026, at the point Flyway was
-- introduced. It is the starting shape every environment builds from; existing
-- databases are stamped as already having it (flyway.baseline-on-migrate),
-- while a fresh database runs it in full.
--
-- Do not edit this file. Schema changes go in new V2, V3... migrations so that
-- every environment applies the same steps in the same order.
--
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activation_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activation_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    attempts integer NOT NULL,
    code_hash character varying(100) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    tenant_id bigint NOT NULL,
    token_hash character varying(100) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL,
    stripe_session_id character varying(120)
);


--
-- Name: activation_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activation_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activation_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_executions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    completion_tokens integer,
    decision character varying(20),
    latency_ms bigint,
    message character varying(500),
    model character varying(60),
    prompt_tokens integer,
    prompt_version character varying(30),
    provider character varying(20) NOT NULL,
    schema_status character varying(20),
    score integer,
    success boolean NOT NULL,
    task character varying(50) NOT NULL,
    total_tokens integer,
    tenant_id bigint,
    CONSTRAINT ai_executions_decision_check CHECK (((decision)::text = ANY ((ARRAY['MATCH'::character varying, 'POSSIBLE_MATCH'::character varying, 'NO_MATCH'::character varying, 'REVIEW'::character varying])::text[]))),
    CONSTRAINT ai_executions_provider_check CHECK (((provider)::text = ANY ((ARRAY['OPENAI'::character varying, 'DETERMINISTIC'::character varying])::text[])))
);


--
-- Name: ai_executions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_executions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_executions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alert_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alert_rules (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    active boolean NOT NULL,
    condition character varying(20) NOT NULL,
    note character varying(300),
    product_id bigint NOT NULL,
    tenant_id bigint,
    threshold_type character varying(10),
    threshold_value numeric(12,2),
    last_fired_at timestamp(6) with time zone,
    last_listing_count integer,
    last_observed_value numeric(12,2),
    trigger_count integer DEFAULT 0 NOT NULL,
    channels character varying(100),
    CONSTRAINT alert_rules_condition_check CHECK (((condition)::text = ANY ((ARRAY['PRICE_DROP'::character varying, 'PRICE_INCREASE'::character varying, 'COMPETITOR_CHANGE'::character varying, 'NEW_SELLER'::character varying, 'OUT_OF_STOCK'::character varying, 'MARGIN_BREACH'::character varying, 'PRICE_GAP'::character varying, 'DATA_STALE'::character varying])::text[])))
);


--
-- Name: alert_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alert_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alert_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    action character varying(100) NOT NULL,
    actor character varying(150) NOT NULL,
    details character varying(1000),
    entity_id character varying(60),
    entity_type character varying(60),
    tenant_id bigint
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competitor_listings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competitor_listings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    condition character varying(30),
    currency character varying(10),
    last_price numeric(12,2),
    marketplace character varying(20) NOT NULL,
    marketplace_item_id character varying(120) NOT NULL,
    match_status character varying(20) NOT NULL,
    product_id bigint NOT NULL,
    seller character varying(150),
    source_timestamp timestamp(6) with time zone,
    title character varying(500),
    url character varying(600),
    availability character varying(20),
    rating double precision,
    shipping numeric(12,2),
    match_score integer,
    last_fetched_at timestamp(6) with time zone,
    tenant_id bigint,
    CONSTRAINT competitor_listings_match_status_check CHECK (((match_status)::text = ANY ((ARRAY['CANDIDATE'::character varying, 'MATCHED'::character varying, 'EQUIVALENT'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: competitor_listings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.competitor_listings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competitor_listings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    email character varying(150) NOT NULL,
    message character varying(2000) NOT NULL,
    name character varying(150) NOT NULL,
    phone character varying(30),
    subject character varying(200)
);


--
-- Name: contact_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cost_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cost_profiles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    advertising numeric(12,2),
    cogs numeric(12,2),
    currency character varying(10),
    duty numeric(12,2),
    fulfilment_fee numeric(12,2),
    inbound_freight numeric(12,2),
    note character varying(500),
    outbound_shipping numeric(12,2),
    overhead_allocation numeric(12,2),
    payment_fee_rate_pct numeric(6,3),
    prep numeric(12,2),
    product_id bigint NOT NULL,
    referral_rate_pct numeric(6,3),
    returns_allowance_pct numeric(6,3),
    storage numeric(12,2),
    tax_rate_pct numeric(6,3),
    valid_from date
);


--
-- Name: cost_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cost_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cost_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demo_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.demo_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    company_name character varying(200),
    email character varying(150) NOT NULL,
    message character varying(1000),
    name character varying(150) NOT NULL,
    phone character varying(30)
);


--
-- Name: demo_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.demo_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demo_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_templates (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    body character varying(8000) NOT NULL,
    edited boolean NOT NULL,
    subject character varying(300) NOT NULL,
    template_key character varying(40) NOT NULL,
    CONSTRAINT email_templates_template_key_check CHECK (((template_key)::text = ANY ((ARRAY['CLIENT_ACTIVATION'::character varying, 'VERIFICATION_CODE'::character varying, 'PASSWORD_RESET'::character varying, 'WELCOME'::character varying, 'PLAN_CHANGE_PAYLINK'::character varying])::text[])))
);


--
-- Name: email_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_errors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_errors (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    error_message character varying(500) NOT NULL,
    field character varying(100),
    raw_data character varying(4000),
    row_number integer NOT NULL,
    sku character varying(100),
    import_job_id bigint NOT NULL
);


--
-- Name: import_errors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_errors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_errors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.import_jobs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    duplicate_count integer NOT NULL,
    error_count integer NOT NULL,
    file_name character varying(300) NOT NULL,
    file_type character varying(10) NOT NULL,
    finished_at timestamp(6) without time zone,
    mapping_json character varying(2000),
    message character varying(1000),
    processed_rows integer NOT NULL,
    started_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    success_count integer NOT NULL,
    total_rows integer NOT NULL,
    CONSTRAINT import_jobs_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['CSV'::character varying, 'XLSX'::character varying])::text[]))),
    CONSTRAINT import_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'COMPLETED_WITH_ERRORS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: import_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.import_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listing_price_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listing_price_snapshots (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    currency character varying(10),
    item_price numeric(12,2),
    landed_price numeric(12,2),
    listing_id bigint NOT NULL,
    observed_at timestamp(6) with time zone NOT NULL,
    shipping numeric(12,2),
    marketplace character varying(20),
    marketplace_item_id character varying(100)
);


--
-- Name: listing_price_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.listing_price_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.listing_price_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketplace_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketplace_configs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    enabled boolean NOT NULL,
    encrypted_credentials character varying(4000),
    last_checked_at timestamp(6) with time zone,
    last_message character varying(500),
    provider character varying(20) NOT NULL,
    status character varying(20),
    CONSTRAINT marketplace_configs_provider_check CHECK (((provider)::text = ANY ((ARRAY['AMAZON'::character varying, 'EBAY'::character varying, 'KEEPA'::character varying])::text[])))
);


--
-- Name: marketplace_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marketplace_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marketplace_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketplace_search_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketplace_search_cache (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    fetched_at timestamp(6) with time zone NOT NULL,
    hit_count integer NOT NULL,
    item_ids text,
    marketplace character varying(20) NOT NULL,
    query_key character varying(500) NOT NULL
);


--
-- Name: marketplace_search_cache_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marketplace_search_cache ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marketplace_search_cache_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: monitors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monitors (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    enabled boolean NOT NULL,
    interval_minutes integer NOT NULL,
    last_message character varying(500),
    last_result_count integer,
    last_run_at timestamp(6) with time zone,
    last_status character varying(20),
    markets character varying(100),
    max_results integer,
    next_run_at timestamp(6) with time zone,
    product_id bigint NOT NULL,
    tenant_id bigint NOT NULL
);


--
-- Name: monitors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.monitors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monitors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: newsletter_subscribers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.newsletter_subscribers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    active boolean NOT NULL,
    email character varying(150) NOT NULL
);


--
-- Name: newsletter_subscribers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.newsletter_subscribers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.newsletter_subscribers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    link character varying(200),
    message character varying(500),
    read boolean NOT NULL,
    read_at timestamp(6) with time zone,
    recipient_user_id bigint NOT NULL,
    tenant_id bigint,
    title character varying(150) NOT NULL,
    type character varying(30) NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(512) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL,
    code_hash character varying(100),
    verified boolean DEFAULT false NOT NULL,
    attempts integer DEFAULT 0 NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    amount numeric(12,2),
    billing_cycle character varying(10),
    currency character varying(10),
    method character varying(30),
    note character varying(300),
    paid_at timestamp(6) with time zone,
    plan_code character varying(50),
    status character varying(20) NOT NULL,
    stripe_session_id character varying(120),
    tenant_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    CONSTRAINT payments_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT payments_type_check CHECK (((type)::text = ANY ((ARRAY['INITIAL'::character varying, 'UPGRADE'::character varying, 'DOWNGRADE'::character varying, 'RENEWAL'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: price_recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.price_recommendations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    break_even_price numeric(12,2),
    competitor_median numeric(12,2),
    confidence numeric(5,1),
    currency character varying(10),
    expected_margin_pct numeric(6,2),
    expires_at date,
    product_id bigint NOT NULL,
    rationale character varying(800),
    recommended_price numeric(12,2),
    status character varying(20) NOT NULL,
    CONSTRAINT price_recommendations_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'APPROVED'::character varying, 'PUBLISHED'::character varying, 'REJECTED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: price_recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.price_recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_attributes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_attributes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    category character varying(150),
    color character varying(100),
    country character varying(100),
    material character varying(150),
    model character varying(150),
    size character varying(100),
    variant character varying(150),
    product_id bigint NOT NULL
);


--
-- Name: product_attributes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_attributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_attributes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    description character varying(500),
    name character varying(150) NOT NULL
);


--
-- Name: product_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_identifiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_identifiers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    marketplace character varying(100),
    normalized_value character varying(200),
    original_value character varying(200) NOT NULL,
    type character varying(30) NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT product_identifiers_type_check CHECK (((type)::text = ANY ((ARRAY['ASIN'::character varying, 'UPC'::character varying, 'EAN'::character varying, 'GTIN'::character varying, 'MPN'::character varying, 'MARKETPLACE_ID'::character varying])::text[])))
);


--
-- Name: product_identifiers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_identifiers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_identifiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    hash character varying(128),
    status character varying(20) NOT NULL,
    image_url text NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT product_images_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    brand character varying(150),
    description character varying(2000),
    height numeric(12,3),
    length numeric(12,3),
    pack_quantity integer NOT NULL,
    sku character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    tenant_id bigint,
    title character varying(500) NOT NULL,
    weight numeric(12,3),
    width numeric(12,3),
    category_id bigint,
    our_price numeric(12,2),
    product_condition character varying(20) DEFAULT 'NEW'::character varying NOT NULL,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DRAFT'::character varying, 'ARCHIVED'::character varying])::text[])))
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profitability_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profitability_snapshots (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    break_even_price numeric(12,2),
    contribution_margin_pct numeric(6,2),
    currency character varying(10),
    net_profit numeric(12,2),
    product_id bigint NOT NULL,
    roi_pct numeric(8,2),
    selling_price numeric(12,2),
    snapshot_date date NOT NULL
);


--
-- Name: profitability_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profitability_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profitability_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raw_source_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raw_source_records (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    checksum character varying(64),
    external_id character varying(200) NOT NULL,
    operation character varying(30) NOT NULL,
    payload text,
    source character varying(30) NOT NULL
);


--
-- Name: raw_source_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.raw_source_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raw_source_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    expiry_date timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(512) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    match_count integer NOT NULL,
    matched_stage character varying(20) NOT NULL,
    query_text character varying(500) NOT NULL,
    trace_json character varying(4000),
    tenant_id bigint,
    CONSTRAINT search_history_matched_stage_check CHECK (((matched_stage)::text = ANY ((ARRAY['ASIN'::character varying, 'GTIN'::character varying, 'EAN'::character varying, 'UPC'::character varying, 'MPN'::character varying, 'SKU'::character varying, 'TITLE'::character varying, 'URL'::character varying, 'IMAGE'::character varying, 'NONE'::character varying])::text[])))
);


--
-- Name: search_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.search_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_jobs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    correlation_id character varying(60),
    finished_at timestamp(6) with time zone,
    markets character varying(100),
    note character varying(1000),
    product_id bigint NOT NULL,
    result_count integer,
    status character varying(20) NOT NULL
);


--
-- Name: search_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.search_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.search_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: self_registrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.self_registrations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    attempts integer NOT NULL,
    billing_cycle character varying(10) NOT NULL,
    city character varying(100),
    code_hash character varying(100) NOT NULL,
    company_address character varying(500),
    company_name character varying(200) NOT NULL,
    company_phone character varying(30),
    contact_person character varying(150),
    country character varying(100),
    created_tenant_id bigint,
    currency character varying(10),
    email character varying(150) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    gstin character varying(40),
    industry character varying(100),
    password_hash character varying(255),
    plan_code character varying(50) NOT NULL,
    postal_code character varying(20),
    state character varying(100),
    status character varying(30) NOT NULL,
    tax_id character varying(40),
    timezone character varying(60),
    token_hash character varying(100) NOT NULL,
    website character varying(200),
    stripe_session_id character varying(120),
    CONSTRAINT self_registrations_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT self_registrations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_VERIFICATION'::character varying, 'VERIFIED'::character varying, 'PENDING_PAYMENT'::character varying, 'COMPLETED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: self_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.self_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.self_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    action character varying(20) NOT NULL,
    end_date date,
    note character varying(500),
    plan_code character varying(50),
    start_date date,
    status character varying(20),
    tenant_id bigint NOT NULL,
    CONSTRAINT subscription_history_status_check CHECK (((status)::text = ANY ((ARRAY['TRIAL'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: subscription_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription_plans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    active boolean NOT NULL,
    billing_cycle_days integer NOT NULL,
    code character varying(50) NOT NULL,
    currency character varying(10),
    description character varying(500),
    features character varying(1000),
    max_users integer NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(12,2) NOT NULL,
    trial_days integer DEFAULT 14 NOT NULL,
    yearly_price numeric(12,2),
    yearly_discount_percent integer,
    min_interval_minutes integer DEFAULT 1440 NOT NULL
);


--
-- Name: subscription_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_cost_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_cost_models (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    advertising numeric(12,2),
    cogs numeric(12,2),
    currency character varying(10),
    marketplace_fees numeric(12,2),
    returns_allowance numeric(12,2),
    shipping numeric(12,2),
    storage numeric(12,2),
    taxes numeric(12,2),
    tenant_id bigint NOT NULL,
    duty numeric(12,2),
    fulfilment_fee numeric(12,2),
    inbound_freight numeric(12,2),
    outbound_shipping numeric(12,2),
    overhead_allocation numeric(12,2),
    payment_fee_rate_pct numeric(6,3),
    prep numeric(12,2),
    referral_rate_pct numeric(6,3),
    returns_allowance_pct numeric(6,3),
    tax_rate_pct numeric(6,3)
);


--
-- Name: tenant_cost_models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenant_cost_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_cost_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_email_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_email_configs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    enabled boolean NOT NULL,
    encrypted_password character varying(2000),
    from_address character varying(200),
    from_name character varying(200),
    host character varying(200),
    last_checked_at timestamp(6) with time zone,
    last_message character varying(500),
    port integer NOT NULL,
    ssl_enabled boolean NOT NULL,
    start_tls boolean NOT NULL,
    status character varying(20),
    tenant_id bigint NOT NULL,
    username character varying(200)
);


--
-- Name: tenant_email_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenant_email_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_email_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_notification_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_notification_channels (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    slack_enabled boolean NOT NULL,
    slack_webhook_url character varying(2000),
    teams_enabled boolean NOT NULL,
    teams_webhook_url character varying(2000),
    tenant_id bigint NOT NULL
);


--
-- Name: tenant_notification_channels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenant_notification_channels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_notification_channels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    city character varying(100),
    company_address character varying(500),
    company_code character varying(50) NOT NULL,
    company_email character varying(150) NOT NULL,
    company_name character varying(200) NOT NULL,
    company_phone character varying(30),
    country character varying(100),
    currency character varying(10),
    logo text,
    max_users integer NOT NULL,
    postal_code character varying(20),
    state character varying(100),
    status character varying(20) NOT NULL,
    subscription_end_date date,
    subscription_plan character varying(50),
    subscription_start_date date,
    subscription_status character varying(20),
    timezone character varying(60),
    website character varying(200),
    contact_person character varying(150),
    industry character varying(100),
    billing_cycle character varying(10),
    gstin character varying(40),
    tax_id character varying(40),
    trial_end_date date,
    scheduled_billing_cycle character varying(10),
    scheduled_plan_code character varying(50),
    scheduled_plan_effective_date date,
    CONSTRAINT tenants_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT tenants_scheduled_billing_cycle_check CHECK (((scheduled_billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT tenants_subscription_status_check CHECK (((subscription_status)::text = ANY ((ARRAY['TRIAL'::character varying, 'ACTIVE'::character varying, 'SUSPENDED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: tenants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    access_type character varying(20),
    email character varying(150) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_login timestamp(6) without time zone,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(30),
    profile_image text,
    status character varying(20) NOT NULL,
    super_admin boolean NOT NULL,
    tenant_id bigint,
    backup_codes character varying(2000),
    two_factor_secret character varying(64),
    two_factor_enabled boolean DEFAULT false NOT NULL,
    CONSTRAINT users_access_type_check CHECK (((access_type)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'ANALYST'::character varying, 'FINANCE'::character varying, 'VIEWER'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activation_tokens activation_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activation_tokens
    ADD CONSTRAINT activation_tokens_pkey PRIMARY KEY (id);


--
-- Name: ai_executions ai_executions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_executions
    ADD CONSTRAINT ai_executions_pkey PRIMARY KEY (id);


--
-- Name: alert_rules alert_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alert_rules
    ADD CONSTRAINT alert_rules_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: competitor_listings competitor_listings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competitor_listings
    ADD CONSTRAINT competitor_listings_pkey PRIMARY KEY (id);


--
-- Name: contact_messages contact_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);


--
-- Name: cost_profiles cost_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cost_profiles
    ADD CONSTRAINT cost_profiles_pkey PRIMARY KEY (id);


--
-- Name: demo_requests demo_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_requests
    ADD CONSTRAINT demo_requests_pkey PRIMARY KEY (id);


--
-- Name: email_templates email_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);


--
-- Name: import_errors import_errors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_errors
    ADD CONSTRAINT import_errors_pkey PRIMARY KEY (id);


--
-- Name: import_jobs import_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_jobs
    ADD CONSTRAINT import_jobs_pkey PRIMARY KEY (id);


--
-- Name: listing_price_snapshots listing_price_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_price_snapshots
    ADD CONSTRAINT listing_price_snapshots_pkey PRIMARY KEY (id);


--
-- Name: marketplace_configs marketplace_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_configs
    ADD CONSTRAINT marketplace_configs_pkey PRIMARY KEY (id);


--
-- Name: marketplace_search_cache marketplace_search_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_search_cache
    ADD CONSTRAINT marketplace_search_cache_pkey PRIMARY KEY (id);


--
-- Name: monitors monitors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitors
    ADD CONSTRAINT monitors_pkey PRIMARY KEY (id);


--
-- Name: newsletter_subscribers newsletter_subscribers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.newsletter_subscribers
    ADD CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: price_recommendations price_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_recommendations
    ADD CONSTRAINT price_recommendations_pkey PRIMARY KEY (id);


--
-- Name: product_attributes product_attributes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_attributes
    ADD CONSTRAINT product_attributes_pkey PRIMARY KEY (id);


--
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);


--
-- Name: product_identifiers product_identifiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_identifiers
    ADD CONSTRAINT product_identifiers_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: profitability_snapshots profitability_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profitability_snapshots
    ADD CONSTRAINT profitability_snapshots_pkey PRIMARY KEY (id);


--
-- Name: raw_source_records raw_source_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_source_records
    ADD CONSTRAINT raw_source_records_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: search_history search_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_history
    ADD CONSTRAINT search_history_pkey PRIMARY KEY (id);


--
-- Name: search_jobs search_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_jobs
    ADD CONSTRAINT search_jobs_pkey PRIMARY KEY (id);


--
-- Name: self_registrations self_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_registrations
    ADD CONSTRAINT self_registrations_pkey PRIMARY KEY (id);


--
-- Name: subscription_history subscription_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_history
    ADD CONSTRAINT subscription_history_pkey PRIMARY KEY (id);


--
-- Name: subscription_plans subscription_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);


--
-- Name: tenant_cost_models tenant_cost_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_cost_models
    ADD CONSTRAINT tenant_cost_models_pkey PRIMARY KEY (id);


--
-- Name: tenant_email_configs tenant_email_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_email_configs
    ADD CONSTRAINT tenant_email_configs_pkey PRIMARY KEY (id);


--
-- Name: tenant_notification_channels tenant_notification_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_notification_channels
    ADD CONSTRAINT tenant_notification_channels_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: activation_tokens uk_activation_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activation_tokens
    ADD CONSTRAINT uk_activation_token_hash UNIQUE (token_hash);


--
-- Name: competitor_listings uk_competitor_listing; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competitor_listings
    ADD CONSTRAINT uk_competitor_listing UNIQUE (product_id, marketplace, marketplace_item_id);


--
-- Name: tenant_cost_models uk_cost_model_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_cost_models
    ADD CONSTRAINT uk_cost_model_tenant UNIQUE (tenant_id);


--
-- Name: cost_profiles uk_cost_profile_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cost_profiles
    ADD CONSTRAINT uk_cost_profile_product UNIQUE (product_id);


--
-- Name: tenant_email_configs uk_email_config_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_email_configs
    ADD CONSTRAINT uk_email_config_tenant UNIQUE (tenant_id);


--
-- Name: email_templates uk_email_template_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT uk_email_template_key UNIQUE (template_key);


--
-- Name: marketplace_configs uk_marketplace_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_configs
    ADD CONSTRAINT uk_marketplace_provider UNIQUE (provider);


--
-- Name: monitors uk_monitor_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitors
    ADD CONSTRAINT uk_monitor_product UNIQUE (product_id);


--
-- Name: newsletter_subscribers uk_newsletter_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.newsletter_subscribers
    ADD CONSTRAINT uk_newsletter_email UNIQUE (email);


--
-- Name: tenant_notification_channels uk_notif_channels_tenant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_notification_channels
    ADD CONSTRAINT uk_notif_channels_tenant UNIQUE (tenant_id);


--
-- Name: product_categories uk_product_categories_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT uk_product_categories_name UNIQUE (name);


--
-- Name: products uk_products_sku; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT uk_products_sku UNIQUE (sku);


--
-- Name: profitability_snapshots uk_profit_snapshot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profitability_snapshots
    ADD CONSTRAINT uk_profit_snapshot UNIQUE (product_id, snapshot_date);


--
-- Name: marketplace_search_cache uk_search_cache_query; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_search_cache
    ADD CONSTRAINT uk_search_cache_query UNIQUE (marketplace, query_key);


--
-- Name: self_registrations uk_self_reg_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.self_registrations
    ADD CONSTRAINT uk_self_reg_token UNIQUE (token_hash);


--
-- Name: subscription_plans uk_subscription_plans_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription_plans
    ADD CONSTRAINT uk_subscription_plans_code UNIQUE (code);


--
-- Name: tenants uk_tenants_company_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk_tenants_company_code UNIQUE (company_code);


--
-- Name: tenants uk_tenants_company_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk_tenants_company_email UNIQUE (company_email);


--
-- Name: tenants uk_tenants_company_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk_tenants_company_name UNIQUE (company_name);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_ai_exec_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_exec_tenant ON public.ai_executions USING btree (tenant_id);


--
-- Name: idx_alert_rule_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_alert_rule_product ON public.alert_rules USING btree (product_id);


--
-- Name: idx_competitor_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_competitor_product ON public.competitor_listings USING btree (product_id, match_status);


--
-- Name: idx_competitor_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_competitor_tenant ON public.competitor_listings USING btree (tenant_id, match_status);


--
-- Name: idx_monitor_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_monitor_due ON public.monitors USING btree (enabled, next_run_at);


--
-- Name: idx_monitor_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_monitor_tenant ON public.monitors USING btree (tenant_id);


--
-- Name: idx_notification_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notification_recipient ON public.notifications USING btree (recipient_user_id, read);


--
-- Name: idx_price_snapshot_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_price_snapshot_item ON public.listing_price_snapshots USING btree (marketplace, marketplace_item_id, observed_at);


--
-- Name: idx_price_snapshot_listing; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_price_snapshot_listing ON public.listing_price_snapshots USING btree (listing_id, observed_at);


--
-- Name: idx_profit_snapshot_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_profit_snapshot_product ON public.profitability_snapshots USING btree (product_id, snapshot_date);


--
-- Name: idx_recommendation_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommendation_product ON public.price_recommendations USING btree (product_id, status);


--
-- Name: idx_search_history_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_history_tenant ON public.search_history USING btree (tenant_id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_identifiers fk57xfy22nrb8476nfv8wqsqmno; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_identifiers
    ADD CONSTRAINT fk57xfy22nrb8476nfv8wqsqmno FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products fk6t5dtw6tyo83ywljwohuc6g7k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk6t5dtw6tyo83ywljwohuc6g7k FOREIGN KEY (category_id) REFERENCES public.product_categories(id);


--
-- Name: product_attributes fkcex46yvx4g18b2pn09p79h1mc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_attributes
    ADD CONSTRAINT fkcex46yvx4g18b2pn09p79h1mc FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: import_errors fks763m91qs6gcmp3w38m1jsjws; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.import_errors
    ADD CONSTRAINT fks763m91qs6gcmp3w38m1jsjws FOREIGN KEY (import_job_id) REFERENCES public.import_jobs(id);


--
-- PostgreSQL database dump complete
--


