-- The landing page's marketing copy — headline, stats row, feature cards,
-- testimonials, FAQs — was written into the React source, so changing a number
-- meant a frontend release. Worse, the copy drifted from the truth: the page
-- promised a 14-day trial for months after the plans stopped offering one.
--
-- One row per section, holding that section's content as JSON. Not a column per
-- field, because the sections have nothing in common: a stat has a value and a
-- suffix, a testimonial has a quote and an author. A table wide enough for both
-- would be mostly nulls, and would need a migration every time the page gained
-- a section.
--
-- Stored as TEXT rather than JSONB. Nothing here is ever queried by field — the
-- whole payload is read and handed to the browser — so JSONB would buy only
-- validation, which the service does anyway with Jackson before saving.
CREATE TABLE landing_content (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6),
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP(6),
    updated_by   VARCHAR(255),
    section      VARCHAR(40)  NOT NULL,
    payload      TEXT         NOT NULL,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_landing_content_section UNIQUE (section)
);

-- Seeded with exactly what the page shows today, so switching the page over to
-- the API changes nothing a visitor can see. Editing starts from the real copy
-- rather than from an empty form.
INSERT INTO landing_content (section, payload, active, created_at, created_by) VALUES

('HERO', '{
  "badge": "AI price monitoring · live across every marketplace",
  "title": "Price with intelligence, not guesswork.",
  "subtitle": "Track competitors, monitor market movements, match your catalog to millions of listings, and let AI recommend the price that protects margin and wins the buy box.",
  "primaryCta": "Start free trial",
  "secondaryCta": "See how it works",
  "assurances": ["No credit card required", "SOC 2 ready"]
}', TRUE, now(), 'V23'),

-- The trial length is deliberately absent above. It is read from the Free plan
-- at request time, so it can never again disagree with what signup charges.

('STATS', '{
  "items": [
    { "value": "12M+",  "label": "Listings tracked daily" },
    { "value": "3.2%",  "label": "Average margin lift" },
    { "value": "45 min","label": "Saved per analyst / day" },
    { "value": "99.9%", "label": "Platform uptime" }
  ]
}', TRUE, now(), 'V23'),

('FEATURES', '{
  "eyebrow": "THE PLATFORM",
  "title": "Everything you need to price competitively",
  "subtitle": "From raw marketplace data to a boardroom-ready recommendation — one connected workflow, no spreadsheets.",
  "items": [
    { "icon": "box",   "title": "Universal matching engine",   "description": "Match your catalog to millions of listings by ASIN, UPC, EAN or image similarity — with confidence scores you can audit." },
    { "icon": "search","title": "Real-time competitor tracking","description": "Watch every seller across Amazon, eBay, Walmart and the open web — price, stock, shipping and condition, updated continuously." },
    { "icon": "trend", "title": "AI pricing recommendations",  "description": "Confidence-scored price moves that protect margin and win the buy box — with the reasoning shown, never a black box." },
    { "icon": "pie",   "title": "Profitability intelligence",  "description": "Model COGS, fees, shipping, ads and returns to see the true net margin behind every SKU and every price change." },
    { "icon": "bell",  "title": "Smart alerts",                "description": "Know the moment a rival drops price, goes out of stock, or a new seller appears — routed to the right person, instantly." },
    { "icon": "report","title": "Boardroom-ready reports",     "description": "Export governed, data-status-tagged reports finance can trust — every number labelled actual, calculated or estimated." }
  ]
}', TRUE, now(), 'V23'),

('HOW_IT_WORKS', '{
  "eyebrow": "HOW IT WORKS",
  "title": "From catalog to confident pricing in three steps",
  "subtitle": "One connected workflow — no spreadsheets, no guesswork, no black boxes.",
  "items": [
    { "step": "01", "title": "Match",    "description": "Import your catalog by CSV or API and auto-match every product against millions of marketplace listings." },
    { "step": "02", "title": "Monitor",  "description": "Continuously track competitor prices, stock, shipping and new sellers across every marketplace you sell on." },
    { "step": "03", "title": "Optimize", "description": "Act on confidence-scored AI recommendations that defend the buy box and protect margin — with the reasoning shown." }
  ]
}', TRUE, now(), 'V23'),

('TESTIMONIALS', '{
  "items": [
    {
      "quote": "Price Intelligence paid for itself in six weeks. We stopped guessing on competitor moves and our pricing team finally trusts a single set of numbers.",
      "name": "Anita Krishnan",
      "role": "Head of Pricing, Northwind Retail",
      "initials": "AK"
    }
  ]
}', TRUE, now(), 'V23'),

('FAQS', '{
  "eyebrow": "FAQ",
  "title": "Questions, answered",
  "items": [
    { "question": "How long is the free plan?",              "answer": "The Free plan runs for its full trial length with no card required. You can move to a paid plan at any point, and your data carries over." },
    { "question": "Which marketplaces do you support?",      "answer": "Amazon and eBay today, with more being added. The supported list is shown when you run your first search." },
    { "question": "Do I need a credit card to start?",       "answer": "Not for the Free plan. Paid plans are charged when you subscribe." },
    { "question": "Can I change plan later?",                "answer": "Yes. Upgrades apply immediately once paid; downgrades take effect at the end of the period you have already paid for." },
    { "question": "What happens when my plan ends?",         "answer": "Your account becomes read-only for a short grace period — you keep access to your data and can renew at any time. Nothing is deleted." }
  ]
}', TRUE, now(), 'V23'),

('CTA', '{
  "title": "Stop guessing. Start pricing with intelligence.",
  "subtitle": "Set up your catalog in minutes. See competitor moves and your first AI recommendation today.",
  "primaryCta": "Start free trial",
  "secondaryCta": "Book a demo"
}', TRUE, now(), 'V23');
